divriots/dockit-core

sass-showcases/src/SassShowcases.js, sass-showcases/src/css-props.js, sass-showcases/src/transition-helper.js, sass-showcases/stories/sass-showcases.stories.js, sass-showcases/stories/tokens.scss
Sass showcasing component accepts a "prefix" to identify which css variables to showcase.
This is not enough to differentiate between `--font-sans` and `--font-weight-bold` for example, as `prefix='--font'` will also showcase the font-weight variables, and this is not correct.
To fix this the `names` attribute was added and can be used as an alternative to `prefix`: it takes a list of css variable names and showcases them.
Can be seen in action here:
https://backlight.dev/edit/4BeMe20hqOWTkdUL2NuJ/sass-showcases/stories/sass-showcases.stories.js?branch=showcase-sass-short-caption@tLlGPKdxk2VRYywCKUXNaV8PFt62
=> "prefix" is not enough for sass showcasing, added "names"

package.json
Sadly, but it's not used anymore anywhere, I forgot to remove it earlier.
Good to mention why for the code history: it's been used before the introduction of the `@tailwindcss/typography`, but that one has certain requirements for how the dark mode is switched, and `dark-theme-utils` didn't fit it. Also I started using StencilJS to remove Lit dependency and prevent all kind of migration issues for `mdjs-layout` users, and `dark-theme-utils` didn't work for StencilJS either. So it was logical to remove it for now.
=> chore: remove unused dependency dark-theme-utils

css-showcases/src/CssShowcases.js, css-showcases/src/alerts.module.scss, css-showcases/src/transition-box.module.scss, css-showcases/src/transition-helper.js, css-showcases/stories/css-showcases.stories.js, css-showcases/stories/tokens.scss
This PR introduces new features in `transitions` showcases:
- `--transition` prefix is still supported but deprecated, should be replaced by `--time`
- support for `mode` allowing to override the render type rather than detecting it _via_ the CSS Custom Property prefix (fix #32)
- add support for `ease` and `animation` custom properties to showcases [CSS `timing-functions`](https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function) and [CSS `animations`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation)
Demo in Backlight: https://backlight.dev/edit/4BeMe20hqOWTkdUL2NuJ/css-showcases/stories/css-showcases.stories.js?branch=css-showcases-modes%40QyIjO3Opm0S4QYLfACyef1GvBgA2&p=stories
=> Css showcases modes

doc-layout/src/template.js, mdjs-layout/doc/index.md, mdjs-layout/src/misc.css, mdjs-layout/src/styles.css
New version of typography:
- less intrusive (pay attention to `.not-prose` in the typography, it's gonna be useful)
- no need for normalize (@jorenbroekema 🎉 )
- based on CSS vars, which we can document at some point too for people to easily customise (big win!)
Some issues:
=> feat(mdjs-layout): upgrade tailwind typography which does not need normalize

mdjs-layout/src/misc.css
Provides automatic theme when api-viewer is used on a page with mdjs-layout, makes it look nice with it.
=> feat(mdjs-layout): style api-viewer and friends in light/dark modes

mdjs-layout/src/mdjs-layout.ts
We need to check for the existence of the color-scheme toggle DOM node before manipulating it.
=> fix(mdjs-layout): prevent render error when color scheme is disabled

css-showcases/src/CssShowcases.js, mdjs-layout/src/mdjs-layout.styles.js
z-index addition is needed to make sure this problem is fixed
and the deprecation message introduced earlier suggests a solution to use `mode="time"`, but when this solution is applied, the deprecation message is still shown, so we need to hide it in that case
=> Bugfixes for starter-vue3

css-showcases/src/CssShowcases.js, css-showcases/src/transition-helper.js
Fixes situation when last `<dockit-css-showcases>` which demoes transition/animations breaks previous instances on the same page. Fix is needed in docs where multiple `<dockit-css-showcases>` can be present easily on the same page.
=> fix(css-showcases): fix multiple instances of transition showcases

mdjs-layout/src/misc.css
On some short pages there might be not enough content to display a scrollbar. This is an issue causing layout shifts (e.g. when navigating between different pages) demonstrated in the video below, so we should enforce a scrollbar to prevent it.
https://user-images.githubusercontent.com/137844/153645978-5ac30d1d-441d-45eb-a4a6-a53bab50b593.mp4
=> fix(mdjs-layout): enforce scroll bar on short pages

box/src/Box.js, box/stories/box.stories.js, css-showcases/src/CssShowcases.js, showcases/src/CaptionedBox.js, showcases/src/Showcases.js, tailwind-showcases/src/TailwindShowcases.js
It used to be the default anyway due to a bug in attribute propagation in most components except the main `dockit-box` one. I'm basically cleaning this without worrying it's gonna break the usage for people and I think it's needed anyway by default always.
Also, as Georges pointed out in https://github.com/divriots/dockit-core/pull/52#discussion_r808747141, people can make another box class if needed to override the checkered styles.
=> feat: make checkered-background always

tailwind-showcases/src/TailwindShowcases.js, tailwind-showcases/stories/tailwind-showcases.stories.js
Turned out we can't always set `checkered-background`, because there are cases (colors) where it makes sense and other cases (border-width, border-radius) where it looks weird with it. Previously there was a bug which added it in some cases for Tailwind, but not for others (also there was same bug for `long-text`). I fixed that bug and opened up a pandora box with other things broken.
This PR tries to finally find a good balance: for Tailwind it's gonna make sure `checkered-background` and `long-text` is set when needed. For other components the situation stays flexible: you know where you need it and need to add it explicitely. The follow-up PR will add clear docs on that.
I assume most of our users right now rely on `dockit-tailwind-showcases`, so this should keep backwards …
=> Tailwind automatic attributes for checkered-background and long-text

layout/src/Layout.ts
Current implementation is hardcoded in the sense that all URLs were assuming it's relative to `/level1/level2/level3`.
This is very inflexible of course, but to be precise:
- no way to make URLs like this with a final slash `/name/doc/name/`, to make consistent with index paths like `/name/doc/`
- no way to remap URLs to make them truly readable for the exported docs (e.g. remap `/name/doc/` to just `/name/` on `http://mysite.docs/name/` with the `base = "/"`)
This PR is one of many which will follow, on adding support for base on all sides of the documentation.
=> feat(layout): use context.base for navigation links

layout/src/Layout.ts
Bug appears when user scroll navigation to the bottom and clicks on the link.
When speedy-links is used, then the page gets rerendered without full page refresh, but the scroll of the navigation is unexpectedly reset.
This workaround is needed for now due to suboptimal rerendering mechanism.
In the future we gonna migrate all dockit-core components to Lit (or similar) and we can get rid of this code given the elements are not just fully replaced on each rerender.
=> fix(layout): prevent incorrect reset of navigation scrollTop when rerendering

layout/src/Layout.ts
When `speedy-links` is used, there is no page refresh, therefore we need to make sure the navigation is hidden on link click in the mobile layout.
=> fix(layout): hide navigation when link is clicked

layout/src/Layout.styles.ts
Trying to provide useful defaults, so that most people don't need to write any styles when they just use an IMG or SVG tag.
This PR adds support for 2 scenarios when IMG tag is used in the logo slot
```html
<dockit-layout>
<div slot="logo">
</div>
</dockit-layout>
<dockit-layout>
</dockit-layout>
```
Previously only inline SVG worked smoothly
```html
<dockit-layout>
<div slot="logo">
<svg>...</svg>
</div>
</dockit-layout>
```
=> fix(layout): scale img tag size when used directly of with div wrapper

layout/doc/layout.md, layout/src/Layout.styles.ts, layout/src/Layout.ts
Some interesting thoughts on this can be found in
https://stackoverflow.com/questions/59015022/css-variables-defaults-set-if-not-already-set
But this PR takes the use-case further and results in the following requirements:
1. `read` access (new requirement solved by this PR)
2. `write` access
3. default values
The combination of all 3 requires an intermediate DOM node and "weird" reassignment:
1. on host: `--my-var` => `--proxy--my-var`
2. on intermediate DOM node: `--proxy--my-var` => `--my-var` with a default value
PS: btw this doesn't work (if you are wondering "why not just give a default value on host?")
```css
:host {
--my-var: var(--my-var, "default-value")
}
```
=> feat(layout): expose default CSS props for reading

speedy-links/src/speedy-links.ts
e.g. when hash is `#smth20%with20%percent20%sign`
=> fix(speedy-links): prevent error when hash is not a valid selector

layout/src/Layout.ts
Solves bug that current active link may not be updated when navigation happens to another page.
In Backlight we now create a `context` module which exports just a single `context` reference, so layout updates set the same `context` reference during navigations and content rendering.
Lit's internal strict equality check now thinks `context` didn't change (nor other props), and because of that the rerendering is not triggered.
We need another way to update current active link.
I tried different approaches:
- ideally we want to monitor some sort of `location-change` event, but platform lacks such an event, there are `popstate` and `hashchange`, but they are not generic and not suitable for `location.pathname` which we need to listen to
- `slotchange` event and MutationObserver of the content …
=> fix(layout): update current link when setting same context object

do-dont/index.js
Sorry, I forgot to remove this file earlier. And now it's breaking release.
PS: we need to discuss and come to conclusion about `component/index.js` files, what to export and what not to to be in good shape for Semantic Versioning. Until then let's please not make such file with `export *`, it's confusing for CE classes and some other exports of internal things which should never
=> fix(do-dont): remove broken file

box/src/Box.module.css, box/src/Box.ts
This has the disadvantage that the checkered background div ignores other styles such as `border-radius` applied to the box - this might be an isolated corner case.
Another option would be to force `opacity: 1 !important;` and apply the showcase class as well to the checkered bg div.
I'm open to other options as well, I just didn't find a better solution.
You can see a before and after in showcase opacity class here
https://studio.backlight.dev/diff/4BeMe20hqOWTkdUL2NuJ/showcases?branch=pr:89@mveres
=> fixed box checkered bg opacity by removing applied class from div

speedy-links/index.ts, speedy-links/src/speedy-links.ts
I forgot to rename this type when renaming the lib to `speedyLinks` before the release, time to fix that.
=> feat(speedy-links): rename type
